name: Build LuaRocks module on Linux

on: [push, pull_request]

jobs:
  build:
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      # fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: checkout c-dt-ffi
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install build prerequisites
        run: |
          sudo apt-get install -y luarocks luajit libluajit-5.1-dev

      - name: Install luacheck and busted
        run: |
          sudo luarocks install LuaFileSystem
          sudo luarocks install luacheck
          sudo luarocks install busted

      - name: Check via luacheck
        run: |
          luacheck --codes .

      - name: luarocks make and pack
        run: |
          luarocks make --local
          luarocks pack --local c-dt-ffi

      - name: test with busted
        run: |
          LUA_PATH="$HOME/.luarocks/share/lua/5.1/?/init.lua;$HOME/.luarocks/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/usr/local/share/lua/5.1/?.lua;" \
          LUA_CPATH="$HOME/.luarocks/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/?.so" \
          busted --lua=luajit

      - name: publishing linux artifact
        uses: actions/upload-artifact@v2
        with:
          name: c-dt-ffi-scm-1.linux-x86_64.rock
          path: c-dt-ffi-scm-1.linux-x86_64.rock
